[pytest]
addopts = --import-mode=importlib
pythonpath =
    tuning_pipeline
    portrait_pipeline
testpaths =
    tuning_pipeline
    portrait_pipeline/build/codex_portrait_pipeline/tests
    portrait_pipeline/build/migration_pipeline/tests
