[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string]$RemoteHost,
    [Parameter(Mandatory = $true)][string]$RemoteProject,
    [Parameter(Mandatory = $true)][string]$LeaseName,
    [Parameter(Mandatory = $true)][string]$ModelPath,
    [Parameter(Mandatory = $true)][string]$ServedModelName,
    [Parameter(Mandatory = $true)][string]$NetworkInterface,
    [Parameter(Mandatory = $true)][string]$InitEnvScript,
    [ValidateSet("codex", "anthropic", "openai_compatible", "deepseek", "command")]
    [string]$AgentProvider = "deepseek",
    [ValidateSet("aligned_l1_v4", "vllm_bench_public_v1", "custom_adapter_v1")]
    [string]$BenchmarkProfile = "vllm_bench_public_v1",
    [ValidateSet("automatic_registry_v1", "curated_registry_v1")]
    [string]$SearchSpaceProfile = "automatic_registry_v1",
    [string]$RuntimeAdapter
)

$ErrorActionPreference = "Stop"
$projectRoot = Split-Path -Parent $PSScriptRoot
$target = Join-Path $projectRoot "tuning_pipeline\workflow\continuous\config.local.yaml"
if (Test-Path -LiteralPath $target) {
    throw "Local config already exists; refusing to overwrite it: $target"
}

function ConvertTo-YamlScalar([string]$Value) {
    return "'" + $Value.Replace("'", "''") + "'"
}

$remoteRoot = $RemoteProject.TrimEnd("/")
$runtimeBlock = ""
if ($RuntimeAdapter) {
    $runtimeBlock = @"

runtime:
  adapter_file: $(ConvertTo-YamlScalar $RuntimeAdapter)
"@
}
$content = @"
# Generated by scripts/init-local-config.ps1. This file is ignored by Git.
base_config: config.yaml

remote_host: $(ConvertTo-YamlScalar $RemoteHost)
remote_project: $(ConvertTo-YamlScalar $remoteRoot)
$runtimeBlock

deployment:
  model_path: $(ConvertTo-YamlScalar $ModelPath)
  served_model_name: $(ConvertTo-YamlScalar $ServedModelName)
  network_interface: $(ConvertTo-YamlScalar $NetworkInterface)
  init_env_script: $(ConvertTo-YamlScalar $InitEnvScript)

lab:
  lease_name: $(ConvertTo-YamlScalar $LeaseName)
  output_root: $(ConvertTo-YamlScalar ($remoteRoot + "/workflow/auto/lab_runs"))

agent:
  provider: $(ConvertTo-YamlScalar $AgentProvider)

benchmark:
  profile: $(ConvertTo-YamlScalar $BenchmarkProfile)

search_space:
  profile: $(ConvertTo-YamlScalar $SearchSpaceProfile)

strategy:
  profile: hierarchical_throughput_v1
"@

Set-Content -LiteralPath $target -Value $content -Encoding utf8
Write-Host "Created local configuration: $target"
if ($RuntimeAdapter) {
    Write-Host "Runtime adapter selected; its topology, image, scenario, B0, Benchmark and Search-Space bindings take precedence."
}
Write-Host "Next: verify remote/image_version_manifest.yaml and activation.approved.yaml."
Write-Host "Then run: .\一键启动.ps1 -CheckOnly -NewSession"
